version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ridge_base
      POSTGRES_USER: ridge_user
      POSTGRES_PASSWORD: ridge_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d/  # Auto-run our schema
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: